title: 'daltonian.github.io'
description: "Author Info and GitHub Repository"
baseurl: "/"
url: "https://daltonian.github.io"

header_pages:
  - index.md
  - dalton.md
  - about.md
  - contact.md

style: light 

footer: 'follow me on <a href="https://twitter.com/nitrocatechol">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
