title: 'daltonian.github.io'
description: "Author Info and GitHub Repository"
baseurl: "/"
url: "https://daltonian.github.io"

header_pages:
  - index.md
  - about.md
  - dalton.md
  - contact.md
  - publications.md
  

include: ['_media']

style: light 

footer: 'follow me on <a href="https://twitter.com/nitrocatechol">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
kramdown:
  parse_block_html: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
