# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Avery Dalton
title: Physical Chemistry
email: avery@daltonian.co
website: https://daltonian.co

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: nitrocatechol
github_username:  yreva
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: avery.pdf
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: daltonian.co
  icon: fas fa-atom fa-fade
  url: https:/daltonian.co
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Avery and I'm currently a graduate student. As well as chemistry, I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark> and <mark>Drinking Coffee</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Daltonian
        link: github.com/yreva
        # link_text: Project Website
        additional_links:
          - title:  DaltonView
            icon: fab fa-github
            url: github.com/daltonian/daltonview
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aerosol Photochemistry Group
        link: aerosol.chem.uci.edu
        # link_text: boringcompany.com
        sub_title: Research Assistant / Safety Officer
        caption: February 2020 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Spectroscopic inquisition in all things nitro.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Irvine
        caption: 2019 - 2024
        sub_title: PhD Physical Chemistry
        quote: >
          Quote about UCI here.
        description: | # this will include new lines to allow paragraphs
          During my time at UCI I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I did little extracurricular work during my PhD as I was putting in maximal effort toward my research projects. I was only either in the ocean or in the lab. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in chemistry and software engineering some of my other interests and hobbies are:
      - Meteorology
      - Surfing
      - Sound Design

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: assets
  style: compressed

plugins:
 - jekyll-seo-tag
