import CSSProvider from "./components/CSSProvider";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/index";
import "./globals.css";

export const metadata = {
  title: "dSign",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CSSProvider />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
